# Generated by Django 3.1.1 on 2020-09-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_auto_20200926_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
