# Generated by Django 3.1.1 on 2020-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_auto_20200926_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='موجود / ناموجود'),
        ),
    ]
