# Generated by Django 3.1.1 on 2020-09-26 07:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0001_initial'),
        ('eshop_products', '0004_product_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_product_category.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
