# Generated by Django 3.1.1 on 2020-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='product_gallery/'),
        ),
    ]
