# Generated by Django 3.1.1 on 2020-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_auto_20201003_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
