# Generated by Django 3.1.1 on 2020-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در url')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(max_length=20, verbose_name='فیمت')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
            ],
        ),
    ]
