# Generated by Django 3.1.1 on 2020-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_tag', '0001_initial'),
        ('eshop_products', '0007_favouriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='eshop_product_tag.ProductTag', verbose_name='تگ'),
        ),
    ]
