# Generated by Django 3.1.1 on 2020-10-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0012_product_visit'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
