# Generated by Django 3.1.1 on 2020-09-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'اطلاعات ما', 'verbose_name_plural': 'اطلاعات ما'},
        ),
    ]
